[package]
name = "r11_lifetimes"
version = "0.1.0"
authors = ["johntucker"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
